session_name: Devenv-Py2Nix
windows:
  - window_name: Devenv-Py2Nix
    layout: main-vertical
    options:
      main-pane-width: 20%
    panes:
      - shell_command:
          - cd ~/Documents/Notes/Projects/devenv-py2nix
          # - nvim Notes.md ToDo.md
          - open-project
      - shell_command:
          - tmux resizep -y 85%
          - filelist-open "startup_files.txt" devenv-py2nix
        focus: true
      - clear
